# generated by fastapi-codegen:
#   filename:  server.yaml
#   timestamp: 2024-01-13T18:45:42+00:00

from __future__ import annotations

from fastapi import APIRouter

from ..dependencies import *

router = APIRouter(tags=['Model'])


@router.post('/v1/models', response_model=V1Model, tags=['Model'])
def load_model(body: V1LoadModelRequest = None) -> V1Model:
    """
    Load a model
    """
    pass


@router.get('/v1/models', response_model=V1Models, tags=['Model'])
def get_models() -> V1Models:
    """
    A list of models
    """
    pass


@router.get('/v1/models/{name}', response_model=V1Model, tags=['Model'])
def get_model(name: str) -> V1Model:
    """
    Get a model
    """
    pass


@router.delete('/v1/models/{name}', response_model=None, tags=['Model'])
def delete_model(name: str) -> None:
    """
    Delete a model
    """
    pass


@router.post('/v1/models/{name}/chat', response_model=V1ChatResponse, tags=['Model'])
def chat(name: str, body: V1ChatRequest = None) -> V1ChatResponse:
    """
    Chat with a model
    """
    pass


@router.post(
    '/v1/models/{name}/generate', response_model=V1GenerateResponse, tags=['Model']
)
def generate(name: str, body: V1GenerateRequest = None) -> V1GenerateResponse:
    """
    Generate text
    """
    pass
