# generated by fastapi-codegen:
#   filename:  server.yaml
#   timestamp: 2024-01-05T05:18:11+00:00

from __future__ import annotations

from frequency.api.v1.server.models import (
    V1Adapter,
    V1Adapters,
    V1GenerateRequest,
    V1GenerateResponse,
    V1Health,
    V1Info,
    V1LoadModelRequest,
    V1Model,
    V1Models,
)
