# generated by fastapi-codegen:
#   filename:  ./frequency/api/v1/server.yaml
#   timestamp: 2024-01-05T05:18:11+00:00

from __future__ import annotations

from typing import Dict, List, Optional

from pydantic import BaseModel


class V1Health(BaseModel):
    status: Optional[str] = None


class V1Info(BaseModel):
    version: Optional[str] = None


class V1LoadModelRequest(BaseModel):
    name: str
    type: str
    hf_repo: str


class V1Model(BaseModel):
    name: str
    type: str
    hf_repo: str
    adapters: Optional[List[str]] = None


class V1Models(BaseModel):
    models: List[V1Model]


class V1ChatHistory(BaseModel):
    __root__: Optional[Dict[str, str]] = None


class V1Adapter(BaseModel):
    name: Optional[str] = None
    uri: str
    model: str


class V1Adapters(BaseModel):
    adapters: List[V1Adapter]


class V1ChatRequest(BaseModel):
    query: str
    adapters: Optional[List[str]] = None
    history: Optional[V1ChatHistory] = None


class V1ChatResponse(BaseModel):
    text: str
    history: Optional[V1ChatHistory] = None
