# generated by fastapi-codegen:
#   filename:  server.yaml
#   timestamp: 2024-01-13T18:45:42+00:00

from __future__ import annotations

from .models import (
    V1Adapter,
    V1Adapters,
    V1ChatRequest,
    V1ChatResponse,
    V1GenerateRequest,
    V1GenerateResponse,
    V1Health,
    V1Info,
    V1LoadModelRequest,
    V1Model,
    V1Models,
)
