# generated by fastapi-codegen:
#   filename:  ./frequency/api/v1/server.yaml
#   timestamp: 2024-01-11T20:40:49+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class V1Health(BaseModel):
    status: Optional[str] = None


class V1Info(BaseModel):
    version: Optional[str] = None


class V1LoadModelRequest(BaseModel):
    name: str
    type: str
    hf_repo: str
    cuda: Optional[bool] = None


class V1Model(BaseModel):
    name: str
    type: str
    hf_repo: str
    cuda: Optional[bool] = None
    adapters: Optional[List[str]] = None


class V1Models(BaseModel):
    models: List[V1Model]


class V1GenerateRequest(BaseModel):
    query: str
    adapters: Optional[List[str]] = None


class V1GenerateResponse(BaseModel):
    text: str


class V1Adapter(BaseModel):
    name: str
    uri: Optional[str] = None
    hf_repo: Optional[str] = None
    model: str


class V1Adapters(BaseModel):
    adapters: List[V1Adapter]
